CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts (
    acc_id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    acc_createTime timestamp DEFAULT now(),
    acc_name TEXT
);

CREATE TABLE IF NOT EXISTS profiles (
    pro_id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    pro_name TEXT,
    pro_location TEXT,
    pro_birthday TEXT,
    pro_gender TEXT,
    pro_breed TEXT,
    pro_aboutme TEXT,
    pro_likes TEXT,
    pro_dislikes TEXT,
    acc_id uuid REFERENCES accounts(acc_id) 
);

INSERT INTO accounts (acc_id, acc_name) VALUES
('cee3a7e6-5339-11ea-8d77-2e728ce88125', 'Tim'),
('cee3aaa2-5339-11ea-8d77-2e728ce88125', 'Bob'),
('e21df604-5339-11ea-8d77-2e728ce88125', 'Jim');

INSERT INTO profiles (pro_name, pro_location, pro_birthday, pro_breed, acc_id, pro_gender) VALUES
('name1', 'Portsmouth', '10/20/2015', 'Pug', 'cee3a7e6-5339-11ea-8d77-2e728ce88125', 'Male'),
('name2', 'Portsmouth', '10/20/2015', 'Pug', 'e21df604-5339-11ea-8d77-2e728ce88125', 'Female'),
('name3', 'Portsmouth', '10/20/2015', 'Pug', 'cee3a7e6-5339-11ea-8d77-2e728ce88125', 'Male');

INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Benny','1/1/2018','Male','black','portsmouth','Some text here','Some likes listed','Some dislikes listed', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Ailey','11/13/2002','Female','Indian red admiral','Lap Lae','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.','Devolved holistic project','Re-contextualized fresh-thinking knowledge base', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Nickolai','08/13/2013','Male','Bontebok','Las Breñas','Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.','Right-sized incremental artificial intelligence','Persistent 4th generation analyzer');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Mellicent','05/12/2007','Female','Netted rock dragon','Ciyu','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.','Persistent clear-thinking customer loyalty','Cross-group executive projection');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Maje','06/25/2009','Male','Monkey, rhesus','København','Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.','Persevering human-resource benchmark','Horizontal reciprocal infrastructure', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Hussein','05/12/2012','Male','African fish eagle','Guacarí','Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.','Team-oriented eco-centric complexity','Triple-buffered reciprocal superstructure');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Tommie','08/03/2014','Male','Savannah deer','Kaolack','Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.','Programmable optimizing ability','Front-line content-based workforce');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Stephana','03/20/2019','Female','Common brushtail possum','Vicente Guerrero','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','Down-sized disintermediate throughput','De-engineered secondary benchmark');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Darsey','06/07/2010','Female','Roller, lilac-breasted','Boissy-Saint-Léger','Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.','Self-enabling clear-thinking concept','Phased neutral focus group');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Dara','07/20/2018','Male','Deer, white-tailed','Tamandaré','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.','Balanced disintermediate emulation','Networked needs-based Graphical User Interface');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Paloma','06/29/2006','Female','Swallow-tail gull','Zouma','Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.','Focused interactive encryption','Cross-platform grid-enabled task-force');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Galen','08/09/2008','Male','Stilt, black-winged','Bobon','Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.','Adaptive executive time-frame','Secured dynamic framework', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Zarah','08/22/2008','Male','Colobus, magistrate black','Laç','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','Robust clear-thinking infrastructure','Face to face clear-thinking function');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Tate','06/23/2000','Female','Roller, lilac-breasted','Batukuta','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.','Total bottom-line alliance','Synergized analyzing system engine');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Melvyn','05/05/2009','Male','Tarantula','Pailou','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','Phased bandwidth-monitored encryption','Managed dedicated framework');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Helen-elizabeth','12/24/2019','Female','Warthog','Papatowai','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.','Mandatory global workforce','Ameliorated reciprocal matrix');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Jerrine','12/08/2002','Female','White-bellied sea eagle','New Washington','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.','Implemented demand-driven encoding','De-engineered empowering algorithm');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Omar','12/01/2014','Male','Agile wallaby','Dzoraghbyur','Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.','Inverse eco-centric interface','Versatile value-added projection');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Elaina','05/21/2007','Female','Black-necked stork','Thị Trấn Thuận Châu','Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.','Visionary tertiary focus group','Polarised neutral groupware');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Melisse','08/15/2014','Male','Greater flamingo','Grande Cache','Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.','Open-architected static system engine','Cloned content-based project');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Sheena','05/11/2005','Female','Sportive lemur','Karkkila','Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.','Innovative modular knowledge user','Public-key responsive circuit', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Lazarus','10/07/2012','Male','Pied cormorant','Bhalil','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.','Networked secondary help-desk','Profound interactive frame');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Ludovico','07/20/2015','Male','California sea lion','Qiaogu','Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.','Seamless multi-state product','Inverse responsive model');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes) VALUES ('Mano','06/06/2000','Male','Lizard, desert spiny','Açu','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.','Robust fault-tolerant productivity','Cross-platform eco-centric toolset');
INSERT INTO profiles(pro_name,pro_birthday,pro_gender,pro_breed,pro_location,pro_aboutme,pro_likes,pro_dislikes, acc_id) VALUES ('Parrnell','05/22/2015','Male','Butterfly, tropical buckeye','Storvik','Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.','Centralized coherent project','Persevering 24/7 collaboration', 'cee3a7e6-5339-11ea-8d77-2e728ce88125');